### PR TITLE
Resolve create() with WriteResult

### PR DESCRIPTION
**Pull request by dmurvihill**
Reopening the [original PR](https://github.com/soumak77/firebase-mock/pull/135) here.

### CODE REVIEW

**Comment by dmurvihill** [comment]
Hi @op, we're running into the same issue here as we did with #31 -- this is only available through `firebase.admin` and not through `firebase`. Needs resolution.

**Comment by joelpoloney** [comment]
> Hi @op, we're running into the same issue here as we did with #31 -- this is only available through `firebase.admin` and not through `firebase`. Needs resolution.

Is this really an issue? Why not support it regardless? What's the downside of adding it in?

**Comment by dmurvihill** [comment]
I'm realizing now that this PR doesn't make the problem any worse than it already is.

We have an issue where if you call `.firestore()` on a mock SDK, you will get a sort of half-regular and half-admin Frankenmock. For instance, `MockFirestoreDocument` has a `create` method even though that method exists only on the admin SDK, but most of its other methods return `Promise<void>` which is consistent with the regular SDK.

You're right that none of that has anything to do with this PR, so I'm going to merge it. Cheers.

**Comment by joelpoloney** [comment]
Thank you 🙏

**Pull request merged**
