### PR TITLE
Fix: Add Boolean support to Query equalTo

### PR DESCRIPTION
**Pull request by Redmega**
Continued PR from [here](https://github.com/soumak77/firebase-mock/pull/167).

Test is failing, investigation needed.

Preliminary thoughts as per @dmurvihill 
> I've been looking into this; I think the priorityComparator method (utils.js:64) is incomplete. It seems to be interested only in priorities of type null, string, and number, ignoring boolean and object values in spite of the Firebase docs.

> There may (not sure) also be a problem with Slice.prototype._inRange (slice.js:85) which might be doing an exclusive rather than an inclusive range.

### CODE REVIEW

**Comment by Redmega** [comment]
The equalTo test is still failing, so I reckon your second point might have merit:

> There may (not sure) also be a problem with Slice.prototype._inRange (slice.js:85) which might be doing an exclusive rather than an inclusive range.

**Comment by Redmega** [comment]
Ok, it seems like
`ref.child(l).priority` for a child of boolean returns a priority of `null`. Looking into where now.

**Comment by Redmega** [comment]
Ok tests are passing now. I believe it was just missing priority in data -- it was left out of null entries because those were "null" priority already. I just needed to add the priority meta fields to the `data.json`

**Comment by Redmega** [comment]
@dmurvihill Any more comments on this? I would like to use this ASAP, my team needs equalTo support in our tests

**Comment by dmurvihill** [comment]
Merging now. Thanks, great contribution and detective work.

**Comment by dmurvihill** [comment]
Published as `v2.3.1`.

**Pull request merged**
